### PR TITLE
Clarify systemd section

### PR DESCRIPTION
**Pull request by augchan42**

### CODE REVIEW

**Review by kostko — COMMENTED** [review]
This doesn't seem right. Maybe this isn't clear, but the existing section refers to the case where you have a systemd service unit defined for your `oasis-node` process (e.g. in `/etc/systemd/system/oasis-node.service`) on a headless server.

Basically the whole documentation assumes the node is running on a headless server, not in a graphical environment. It is true that systemd is also used to start services on more desktop-oriented distribution configurations, but I don't think this should be among the supported way of running nodes.

**Comment by augchan42** [comment]
This was just what I experienced while trying to get it running on my Azure Ubuntu instance.  I didn't even realize I was running systemd, I was unable to increase the file limit.  See https://superuser.com/questions/1200539/cannot-increase-open-file-limit-past-4096-ubuntu for details.

**Comment by kostko** [comment]
How are you running your `oasis-node` process? So you didn't create a separate systemd service unit for it?

**Comment by augchan42** [comment]
Not yet, I'm still in the middle of setting it up.  Let me try to find where in the doc it tells me how to do this.

**Comment by augchan42** [comment]
Ok, I think better way to go is to add some detail around running oasis-core as systemd system in our docs, and that running oasis-core from graphical (which uses systemd user) is not recommended.

**Pull request closed without merging**
